# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

homepage:

homepage_mobile:
  - label: Ultimate
    title: Ultimate 
    path: pagina/ultimate    
    top: true
  - label: Disc Golf
    path: pagina/discgolf
    top: true
  - label: Organisatie
    path: paginas/organisatie
    top: true
  - label: Spelers
    path: paginas/spelers
    top: true
 
ultimate:
  - label: Ultimate
    title: Ultimate 
    path: pagina/ultimate
  - label: Speluitleg
    path: /pagina/ultimate-speluitleg
  - label: Jeugd
    title: Jeugd Ultimate 
    path: pagina/ultimate-jeugd
    top: true
  - label: Spirit of the Game
    path: pagina/ultimate-spirit-of-the-game
  - label: Nationale teams
    path: pagina/ultimate-nationale-teams
    top: true
  - label: Competitie
    path: paginas/ultimate-competitie
    top: true    
  - label: Verenigingen
    path: pagina/ultimate-spelen
    top: true
  - label: Nieuws
    path: pagina/ultimate-nieuws
    
      
discgolf:
  - label: Disc Golf
    title: Disc Golf
    path: pagina/discgolf
  - label: Speluitleg
    path: /pagina/discgolf-speluitleg    
  - label: Courses
    title: Disc Golf Courses
    path: pagina/discgolf-courses
    top: true
  - label: Competitie
    title: Disc Golf Competitie
    path: pagina/discgolf-competitie
    top: true    
  - label: Verenigingen
    path: pagina/discgolf-spelen
    top: true
  - label: Nieuws
    path: pagina/discgolf-nieuws    
    
organisatie:
  - label: Organisatie
    title: Organisatie
    path: paginas/organisatie
    top: true
  - label: Kader
    title: Organisatie Kader
    path: pagina/organisatie-kader
    top: true
  - label: Documenten
    title: Organisatie Documenten
    path: pagina/organisatie-beleid
    top: true
  - label: Verenigingsondersteuning
    title: Verenigingsondersteuning
    path: pagina/organisatie-verenigingen
    top: true
  - label: Records
    title: Records
    path: pagina/records
    top: true    
  - label: Pers
    title: Pers
    path: pagina/organisatie-pers
    top: true
  - label: Contact
    title: Contact
    path: pagina/organisatie-contact
    top: true
  - label: Nieuws
    title: Organisatie Nieuws
    path: pagina/organisatie-nieuws
  
    
spelers:
  - label: Spelersinfo
    title: Spelersinfo
    path: pagina/spelers
  - label: Ultimate competitie
    title: Spelershome
    path: pagina/spelers-ultimate-competitie
    top: true
  - label: Ultimate jeugdcompetitie
    title: Jeugdcompetitie
    path: pagina/spelers-ultimate-jeugd-competitie
    top: true    
  - label: Disc Golf competitie
    title: Spelershome
    path: pagina/spelers-discgolf-competitie
    top: true
  - label: Programma's
    title: Programma's
    path: pagina/spelers-programmas
    top: true
  - label: Overige sporten
    title: Overige sporten
    path: pagina/overige-sporten
    top: true
  - label: Agenda
    title: Agenda
    path: /pagina/agenda
    top: true
