# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: http://docs.bolt.cm/taxonomies#taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: categories
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    multiple: false
    #listing_template: tag-listing.twig #custom template
    options: [ algemeen, jeugd, studenten, nationale-teams, competitie, kader ] 

competities:
    slug: competities
    singular_slug: competitie
    behaves_like: categories
    multiple: true
    options: [ jeugd, volwassenen, dames, open, mixed, outdoor, indoor ] 

afdelingen: 
    name: Afdelingen
    slug: afdelingen
    singular_name: Afdeling
    singular_slug: afdeling
    behaves_like: grouping
    multiple: false
    options: [ ultimate, discgolf, organisatie, spelers, homepage ]
    
verenigingsaanbod: 
    name: Aanbod
    slug: verenigingsaanbod
    singular_name: Aanbieding
    singular_slug: aanbieding
    behaves_like: categories
    multiple: true
    options: [ ultimate-jeugd, ultimate-studenten, ultimate-volwassenen, discgolf-jeugd, discgolf-volwassenen ]

documentcategorien: 
    name: Documentcategorien
    slug: documentcategorien
    singular_name: Documentcategorie
    singular_slug: documentcategorie
    behaves_like: categories
    multiple: true
    options: [ ultimate, organisatie, discgolf, spelers, beleid, reglementen, verenigingen, kader, competitie, senioren, jeugd, formulieren ]
